// See https://aka.ms/new-console-template for more information
using System;
using System.IO;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
if (args.Length < 2)
{
    Console.WriteLine("Usage: ODataRoslynSplitter <input.cs> <outputDir>");
    return 1;
}

var inputPath = args[0];
var outputDir = args[1];

if (!File.Exists(inputPath))
{
    Console.WriteLine($"Input file not found: {inputPath}");
    return 1;
}

Directory.CreateDirectory(outputDir);

var sourceText = File.ReadAllText(inputPath);
var tree = CSharpSyntaxTree.ParseText(sourceText);
var root = (CompilationUnitSyntax)tree.GetRoot();

// Top-level usings (we'll reuse these in every file)
var usings = root.Usings;

// Handle both block & file-scoped namespaces by using BaseNamespaceDeclarationSyntax
var namespaceNodes = root.Members
    .OfType<BaseNamespaceDeclarationSyntax>()
    .ToList();

if (namespaceNodes.Count == 0)
{
    Console.WriteLine("No namespaces found in the input file.");
    return 1;
}

var headerTrivia = SyntaxFactory.ParseLeadingTrivia(
    $"""
     // <auto-generated>
     //     This code was split from the original OData output.
     //     Generated On: {DateTime.UtcNow:yyyy-MM-ddTHH:mm:ssZ}
     // </auto-generated>

     #nullable enable

     """
);

foreach (var nsNode in namespaceNodes)
{
    var nsName = nsNode.Name.ToString();

    // All top-level type declarations in this namespace
    var typeDecls = nsNode.Members
        .OfType<BaseTypeDeclarationSyntax>() // class, struct, interface, enum, record
        .ToList();

    if (typeDecls.Count == 0)
    {
        continue;
    }

    // Group partials of the same type name
    var groups = typeDecls.GroupBy(t => t.Identifier.ValueText);

    foreach (var group in groups)
    {
        var typeName = group.Key;

        var typeMembers = List<MemberDeclarationSyntax>(group.Cast<MemberDeclarationSyntax>());

        var newNamespaceNode = NamespaceDeclaration(ParseName(nsName))
            .WithMembers(typeMembers);

        var nullableDirective = Trivia(
            NullableDirectiveTrivia(
                Token(SyntaxKind.EnableKeyword).WithLeadingTrivia(Space),
                isActive: true
            )
        );

        var compilationUnit = CompilationUnit()
            .WithUsings(usings)
            .AddMembers(newNamespaceNode)
            .NormalizeWhitespace()
            .WithLeadingTrivia(headerTrivia);

        var code = compilationUnit.ToFullString();

        // --- folder per namespace part ---
        var nsSegments = nsName.Split('.').Skip(1).ToArray();
        var nsRelativeDir = nsSegments.Length > 0
            ? Path.Combine(nsSegments)
            : string.Empty;

        var targetDir = string.IsNullOrEmpty(nsRelativeDir)
            ? outputDir
            : Path.Combine(outputDir, nsRelativeDir);

        Directory.CreateDirectory(targetDir);

        var fileName = Path.Combine(targetDir, $"{typeName}.cs");
        File.WriteAllText(fileName, code);
        Console.WriteLine($"Wrote {fileName}");
    }
}

return 0;
